version: '3.9'

services:
  scrapapi:
    image: scrapapi
    container_name: scrapi
    ports:
      - "8008:80"
    restart: unless-stopped
  portia:
    image: scrapinghub/portia
    container_name: portia
    ports:
      - "8010:9001"
    volumes:
      - ./portia_projects:/app/data/projects:rw
    restart: unless-stopped